apiVersion: v1
kind: Pod
metadata:
  name: google-crawler
spec:
  hostNetwork: true
  containers:
  - name: google-crawler
    image: chkao777/tsmc-project:crawler
    imagePullPolicy: Always 
---
apiVersion: v1
kind: Pod
metadata:
  name: google-crawler-controller
spec:
  hostNetwork: true
  containers:
  - name: google-crawler-controller
    image: chkao777/tsmc-project:crawler-controller
    imagePullPolicy: Always 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      hostNetwork: true
      containers:
      - name: mongo
        image: mongo
        imagePullPolicy: IfNotPresent 
        ports:
          - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    role: leader
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        role: leader
        tier: backend
    spec:
      containers:
      - name: leader
        image: redis:alpine
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    role: leader
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: leader
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: single-worker
  template:
    metadata:
      labels:
        app: single-worker
    spec:
      hostNetwork: true
      containers:
      - name: worker
        image: chkao777/tsmc-project:worker
        imagePullPolicy: Always 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeserver
  template:
    metadata:
      labels:
        app: nodeserver
    spec:
      hostNetwork: true
      containers:
      - name: nodeserver
        image: chkao777/tsmc-project:nodeserver
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
        app: rq-dashboard
        tier: frontend
  template:
    metadata:
      labels:
        app: rq-dashboard
        tier: frontend
    spec:
      containers:
      - name: rq-dashboard
        image: docker.io/jayzhan/tsmc-project:rq-dashboard
        env:
        - name: GET_HOSTS_FROM
          value: "dns"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: rq-dashboard
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 5000  
  selector:
    app: rq-dashboard
    tier: frontend
